#!/bin/bash -l

# Enable the Database secrets engine
echo -e "vault secrets enable -path=lob_a/workshop/database database" >> /root/.bash_history
vault secrets enable -path=lob_a/workshop/database database

exit 0
