#!/bin/bash -l

# List Vault Secrets
echo -e "vault secrets list" >> /root/.bash_history
vault secrets list

# Enable the Database secrets engine
echo -e "vault secrets enable -path=lob_a/workshop/database database" >> /root/.bash_history
vault secrets enable -path=lob_a/workshop/database database

exit 0
