#!/bin/sh -l

# Get the root token from /root/token
export VAULT_TOKEN=$(cat /root/token)

# Mount the userpass auth method
echo -e "vault auth enable userpass" >> /root/.bash_history
vault auth enable userpass

# Create a user
echo -e "vault write auth/userpass/users/harry password=hairy" >> /root/.bash_history
vault write auth/userpass/users/harry password=hairy

# Login
echo -e "vault login -method=userpass username=harry password=hairy" >> /root/.bash_history
vault login -method=userpass username=harry password=hairy

# Unset VAULT_TOKEN
echo -e "unset VAULT_TOKEN" >> /root/.bash_history
unset VAULT_TOKEN

# Lookup the token
echo -e "vault token lookup" >> /root/.bash_history
vault token lookup

# Try to read the secret
echo -e "vault kv get kv/a-secret" >> /root/.bash_history
vault kv get kv/a-secret

exit 0
