# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "3"
secrets:
  - name: HC_VAULT_LICENSE
virtualmachines:
- name: kubernetes
  image: instruqt/k3s-v1-27-1
  shell: /bin/bash
  machine_type: n1-standard-4
