#!/bin/sh -l

set -e

grep -q "vault server -config=/vault/config/vault-config.hcl" /root/.bash_history || fail-message "You haven't run your Vault server yet."

grep -q "vault operator init -key-shares=1 -key-threshold=1" /root/.bash_history || fail-message "You haven't run initialized your server with 'vault operator init -key-shares=1 -key-threshold=1' yet."

grep -q "export VAULT_TOKEN" /root/.bash_history || fail-message "You haven't exported your VAULT_TOKEN yet."

grep -q "vault operator unseal" /root/.bash_history || fail-message "You haven't unsealed your server with 'vault operator unseal' yet."

grep -q "vault status" /root/.bash_history || fail-message "You haven't checked the status of your server with 'vault status' yet."

exit 0
