#!/bin/sh -l

# Write vault-config.hcl
cat <<-EOF > /vault/config/vault-config.hcl
listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 0
}
storage "file" {
  path = "/vault/file"
}
disable_mlock = true
ui=true
EOF

exit 0
