#!/bin/bash -l

#Enable bash history
HISTFILE=/root/.bash_history
set -o history

# List Vault Secrets
vault secrets list

# Enable the Transit secrets engine
vault secrets enable -path=lob_a/workshop/transit transit

exit 0
