#!/bin/bash -l

# Generate creds for the workshop-app role using the Vault CLI
echo -e "vault read lob_a/workshop/database/creds/workshop-app" >> /root/.bash_history
{ read LEASE_ID; } < <(vault read -format=json lob_a/workshop/database/creds/workshop-app | jq -r '.lease_id')

# Extend the lease of the credentials by 2 minutes
echo -e "vault write sys/leases/renew lease_id=\"${LEASE_ID}\" increment=\"120\"" >> /root/.bash_history
vault write sys/leases/renew lease_id="${LEASE_ID}" increment="120"

# Lookup the lease of the credentials
echo -e "vault write sys/leases/lookup lease_id=\"${LEASE_ID}\" increment=\"120\"" >> /root/.bash_history
vault write sys/leases/lookup lease_id="${LEASE_ID}"

# Revoke the credentials
echo -e "vault write sys/leases/revoke lease_id=\"${LEASE_ID}\"" >> /root/.bash_history
vault write sys/leases/revoke lease_id="${LEASE_ID}"

exit 0
