kind: Service
apiVersion: v1
metadata:
  name: vault-go-demo
spec:
  selector:
    app: vault-go-demo
    version: v1
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: LoadBalancer