#!/bin/bash -l

set -e

# Install curl
apk add curl

# Install jq
apk add jq

# Write vault-config.hcl
cat <<-EOF > /vault/config/vault-config.hcl
listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 1
}
storage "file" {
  path = "/vault/file"
}
disable_mlock = true
api_addr = "http://localhost:8200"
ui=true
EOF

exit 0
