#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Download the vault-ssh-helper
wget https://releases.hashicorp.com/vault-ssh-helper/0.2.0/vault-ssh-helper_0.2.0_linux_amd64.zip

# Unzip the vault-ssh-helper in /usr/local/bin
sudo unzip -q vault-ssh-helper_0.2.0_linux_amd64.zip -d /usr/local/bin

# Set vault-ssh-helper to executable
sudo chmod 0755 /usr/local/bin/vault-ssh-helper

# Set the user and group of vault-ssh-helper to root.
sudo chown root:root /usr/local/bin/vault-ssh-helper

# Create a directory to store the configuration file.
sudo mkdir /etc/vault-ssh-helper.d/

# Create the configuration file /etc/vault-ssh-helper.d/config.hcl.
sudo tee /etc/vault-ssh-helper.d/config.hcl <<EOF
vault_addr = "http://base:8200"
tls_skip_verify = true
ssh_mount_point = "ssh"
allowed_roles = "*"
EOF

# Disable common-auth.
sudo sed -i 's/@include common-auth/# @include common-auth/' /etc/pam.d/sshd

# Add authentication verification through the vault-ssh-helper.
echo -e "\nauth requisite pam_exec.so quiet expose_authtok log=/var/log/vault-ssh.log /usr/local/bin/vault-ssh-helper -dev -config=/etc/vault-ssh-helper.d/config.hcl
auth optional pam_unix.so not_set_pass use_first_pass nodelay" | sudo tee -a /etc/pam.d/sshd

# Enable ChallengeResponseAuthentication.
sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config

# Restart the SSHD service.
sudo systemctl restart sshd

exit 0
